### ISSUE TITLE
sortOrder descending of facets

### ISSUE THREAD

**Issue by AppWerft** [subugoe/typo3-find#159]
Hi,
I try to show all publicationYears descending by year.

facets.pubYear.sortOrder = publicationYear desc 
facets.pubYear.sortOrder = publicationYear+desc 
facets.pubYear.sortOrder = publicationYear%20desc

Nothings helps

**Comment by mh-goe** [comment]
Hi, 
thx for your question. Unlike sorting the results on facets you can have the list of facet terms ordered by the number of the results using _count_ (default, only desc) or alphanumerical (0..9a..z only asc) using _index_ (cf. https://github.com/subugoe/typo3-find#facets).

Hope this will solve the issues with that.

**Comment by AppWerft** [comment]
Thanks for quick response.
I have not completely understand how I can sort by facets desc. My goal is to sort by pubyear, not by count of hits. Any ideas?

**Comment by mh-goe** [comment]
Afaik there is no other facet sorting than _count_ oder _index_. Maybe I misunderstood - are you trying to sort the results list (cf. https://github.com/subugoe/typo3-find#sorting) or the years within the facet "Erscheinungsjahr"?

**Comment by AppWerft** [comment]
The "Erscheinungsjahr" should sort chronically and the newest year (2019) should place on top. Is it possible to play with "query"- property?

**Comment by AppWerft** [comment]
Where I can patch the code? If there no standard way I would solve it by  Javascript.

**Comment by mh-goe** [comment]
Since Solr 5 (?) there might be a way to solve this issue by using the [Solr JSON Facet API](https://lucene.apache.org/solr/guide/7_5/json-facet-api.html). At the moment I don't see any standard solution for the code to be patched.

Two possible workarounds without patching this extension come to my mind:
1. Use Javascript or a custom ViewHelper on the respective facets.
2. Index the field "Erscheinungsjahr" on a second field for each record for instance "ErscheinungsjahrDesc" and add a prefix to the values like this: "10000:1995", "9990:1996", "9980:1997", "9970:1998" and so on. Then use this field for the facet and only show the content right to the colon.

**Comment by AppWerft** [comment]
Thanks, I will try to build an custom type like `ListReverse` and try it with fluid. No idea how.

**Comment by AppWerft** [comment]
OK, I have added a new property named `displayReverse` to facets. So I can insert `reverse="true"` into iterator.
